#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# vscode
rm -rf $HOME/Library/Application\ Support/Code/User/Snippets
rm -rf $HOME/Library/Application\ Support/Code/User/settings.json
rm -rf $HOME/Library/Application\ Support/Code/User/keybindings.json
ln -s $DOTFILES/vscode/snippets $HOME/Library/Application\ Support/Code/User/Snippets
ln -s $DOTFILES/vscode/settings.json $HOME/Library/Application\ Support/Code/User/settings.json
ln -s $DOTFILES/vscode/keybindings.json $HOME/Library/Application\ Support/User/Code/keybindings.json

rm -rf $HOME/.zshrc
rm -rf $HOME/.zsh_aliases
ln -s $DOTFILES/.zshrc $HOME/.zshrc
ln -s $DOTFILES/.zsh_aliases $HOME/.zsh_aliases

rm -rf $HOME/.hushlogin
ln -s $DOTFILES/.hushlogin $HOME/.hushlogin

rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor
