#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

# Kitty terminal
rm -rf $HOME/.config/kitty
ln -s $DOTFILES/kitty $HOME/.config

# Tmux
rm -rf $HOME/.tmux.conf
ln -s $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

rm -rf $HOME/.zshrc
rm -rf $HOME/.zsh_aliases
ln -s $DOTFILES/.zshrc $HOME/.zshrc
ln -s $DOTFILES/.zsh_aliases $HOME/.zsh_aliases

rm -rf $HOME/.hushlogin
ln -s $DOTFILES/.hushlogin $HOME/.hushlogin

rm -rf $HOME/.config/phpactor
ln -s $DOTFILES/phpactor $HOME/.config/phpactor

sudo cp scripts/tmux-sessionizer /usr/local/bin/
